definitions:
  models.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact: {}
  title: go-gin-backend
  version: "1.0"
paths:
  /health:
    get:
      description: Health Check Endpoint that doesn't require authentication
      responses:
        "200":
          description: Success
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Health Check
      tags:
      - health
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
